Q_C_API_KEY = "suryachettri24@gmail.com_266c960a-5e74-4f19-9ea2-c62e0f4a31e0"
MONGO_DB_URL = "mongodb://localhost:27017"
DB_NAME = "WALRUS"
DB_COLLECTION = "unique_hosts"
QUALYS_API_URL = "https://api.recruiting.app.silk.security/api/qualys/hosts/get?skip=0&limit=1"
CROWDSTRIKE_API_URL = "https://api.recruiting.app.silk.security/api/crowdstrike/hosts/get?skip=0&limit=1"
SCANNED_HOST = "https://api.recruiting.app.silk.security/api/tenable/hosts/get"
